# Generated by Django 5.1.1 on 2024-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
