# Generated by Django 5.1.1 on 2024-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'Ожидает'), (1, 'В процессе'), (2, 'Выполнено'), (3, 'Отложено'), (4, 'Архив')], default=0, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
    ]
