# Generated by Django 5.1.1 on 2024-10-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
