# Generated by Django 5.1.1 on 2024-09-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Тип ресурса')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Область')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('on_hold', 'Отложенный')], default='active', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Область')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('on_hold', 'Отложенный')], default='active', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='para.area')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Область')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('on_hold', 'Отложенный')], default='active', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='para.area')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='para.project')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='para.resourcetype', verbose_name='Тип ресурса')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ('title',),
            },
        ),
    ]
