# Generated by Django 5.1.1 on 2024-09-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para', '0002_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
    ]
