# Generated by Django 5.1.1 on 2024-09-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para', '0003_alter_area_title_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='para.area'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='para.area'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='para.project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='para.resourcetype', verbose_name='Тип ресурса'),
        ),
    ]
