# Generated by Django 5.1.1 on 2024-09-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ParaTag',
        ),
        migrations.RenameModel(
            old_name='TaggedItem',
            new_name='ParaTaggedItem',
        ),
    ]
