# Generated by Django 5.1.1 on 2024-10-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_rename_tag_paratag_rename_taggeditem_parataggeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paratag',
            options={'ordering': ('title',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='paratag',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип Контента'),
        ),
        migrations.AddField(
            model_name='paratag',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParaTaggedItem',
        ),
    ]
