# Generated by Django 5.1.1 on 2024-10-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paratag_options_paratag_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paratag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='paratag',
            name='object_id',
        ),
    ]
