# Generated by Django 5.1.1 on 2024-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paratag_content_type_remove_paratag_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paratag',
            options={'ordering': ('title',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='paratag',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tag'),
        ),
    ]
